#-------------------------------------------------
#
# Project created by QtCreator 2019-08-16T15:33:07
#
#-------------------------------------------------

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = QgnuRadio
TEMPLATE = app

# The following define makes your compiler emit warnings if you use
# any feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS HIER_BLOCK2_DETAIL_DEBUG TRY_SHM_VMCIRCBUF HAVE_SYS_SHM_H

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0
CONFIG+=rtti
CONFIG += c++11
INCLUDEPATH+=/home/bekl/gnuRadio/gnuradio-3.8.0-QT/QgnuRadio/gnuradio-runtime/include \
/home/bekl/gnuRadio/gnuradio-3.8.0-QT/QgnuRadio/gr-blocks/include\
/home/bekl/gnuRadio/gnuradio-3.8.0-QT/QgnuRadio/gr-blocks/lib \
/home/bekl/gnuRadio/gnuradio-3.8.0-QT/QgnuRadio/gnuradio-runtime/lib \
/home/bekl/gnuRadio/gnuradio-3.8.0-QT/QgnuRadio/gnuradio-runtime/lib/controlport \
/home/bekl/gnuRadio/gnuradio-3.8.0-QT/QgnuRadio/gr-beklBlk/include \
/home/bekl/gnuRadio/gnuradio-3.8.0-QT/QgnuRadio/gr-beklBlk/lib \
/home/bekl/gnuRadio/gnuRadioLibs/include \
/home/bekl/gnuRadio/gnuradio-3.8.0-QT/QgnuRadio/gr-beklBlk/include

LIBS+=-L/home/bekl/gnuRadio/gnuRadioLibs/lib

#LIBS+=-lgnuradio-blocks -lgnuradio-audio

LIBS+=-lboost_atomic  -lboost_math_tr1 \
-lboost_chrono      -lboost_prg_exec_monitor\
-lboost_container   -lboost_program_options\
-lboost_context     -lboost_random\
-lboost_contract    -lboost_regex\
-lboost_coroutine   -lboost_serialization\
-lboost_date_time   -lboost_stacktrace_addr2line\
-lboost_filesystem  -lboost_stacktrace_backtrace\
-lboost_graph       -lboost_stacktrace_basic\
-lboost_iostreams   -lboost_stacktrace_noop\
-lboost_locale      -lboost_system\
-lboost_log_setup   -lboost_thread\
-lboost_log         -lboost_timer\
-lboost_math_c99f   -lboost_type_erasure\
-lboost_math_c99l   -lboost_unit_test_framework\
-lboost_math_c99    -lboost_wave\
-lboost_math_tr1f   -lboost_wserialization\
-lboost_math_tr1l -llog4cpp \
-lgmp -lvolk -lgnuradio-audio

SOURCES += \
        gnuradio-runtime/lib/basic_block.cc \
        gnuradio-runtime/lib/block.cc \
        gnuradio-runtime/lib/block_detail.cc \
        gnuradio-runtime/lib/block_executor.cc \
        gnuradio-runtime/lib/block_gateway_impl.cc \
        gnuradio-runtime/lib/block_registry.cc \
        gnuradio-runtime/lib/buffer.cc \
        gnuradio-runtime/lib/circular_file.cc \
        gnuradio-runtime/lib/constants.cc \
        gnuradio-runtime/lib/controlport/rpcmanager.cc \
        gnuradio-runtime/lib/controlport/rpcserver_aggregator.cc \
        gnuradio-runtime/lib/controlport/rpcserver_booter_aggregator.cc \
        gnuradio-runtime/lib/controlport/rpcserver_selector.cc \
        gnuradio-runtime/lib/controlport/thrift/thrift_application_base.cc \
        gnuradio-runtime/lib/feval.cc \
        gnuradio-runtime/lib/flat_flowgraph.cc \
        gnuradio-runtime/lib/flowgraph.cc \
        gnuradio-runtime/lib/hier_block2.cc \
        gnuradio-runtime/lib/hier_block2_detail.cc \
        gnuradio-runtime/lib/high_res_timer.cc \
        gnuradio-runtime/lib/io_signature.cc \
        gnuradio-runtime/lib/local_sighandler.cc \
        gnuradio-runtime/lib/logger.cc \
        gnuradio-runtime/lib/math/fast_atan2f.cc \
        gnuradio-runtime/lib/math/fxpt.cc \
        gnuradio-runtime/lib/math/random.cc \
        gnuradio-runtime/lib/math/sincos.cc \
        gnuradio-runtime/lib/message.cc \
        gnuradio-runtime/lib/messages/msg_accepter1.cc \
        gnuradio-runtime/lib/messages/msg_accepter_msgq.cc \
        gnuradio-runtime/lib/messages/msg_producer.cc \
        gnuradio-runtime/lib/messages/msg_queue1.cc \
        gnuradio-runtime/lib/misc.cc \
        gnuradio-runtime/lib/msg_accepter.cc \
        gnuradio-runtime/lib/msg_handler.cc \
        gnuradio-runtime/lib/msg_queue.cc \
        gnuradio-runtime/lib/pagesize.cc \
        gnuradio-runtime/lib/pmt/pmt.cc \
        gnuradio-runtime/lib/pmt/pmt_io.cc \
        gnuradio-runtime/lib/pmt/pmt_pool.cc \
        gnuradio-runtime/lib/pmt/pmt_serialize.cc \
        gnuradio-runtime/lib/pmt/pmt_unv.cc \
        gnuradio-runtime/lib/prefs.cc \
        gnuradio-runtime/lib/threadexceptionhandle.cpp \
        gr-beklBlk/lib/RngLib.cpp \
        gr-beklBlk/lib/beklAmpAnalysis_impl.cc \
        gr-beklBlk/lib/beklAntennaPrehandle_impl.cc \
        gr-beklBlk/lib/beklUdpSource_impl.cc \
        gr-beklBlk/lib/beklUdpSourece_impl.cc \
        gr-blocks/lib/abs_blk_impl.cc \
        gr-blocks/lib/add_blk_impl.cc \
        gr-blocks/lib/add_const_bb_impl.cc \
        gr-blocks/lib/add_const_cc_impl.cc \
        gr-blocks/lib/add_const_ff_impl.cc \
        gr-blocks/lib/add_const_ii_impl.cc \
        gr-blocks/lib/add_const_ss_impl.cc \
        gr-blocks/lib/add_const_v_impl.cc \
        gr-blocks/lib/and_blk_impl.cc \
        gr-blocks/lib/and_const_impl.cc \
        gr-blocks/lib/annotator_1to1_impl.cc \
        gr-blocks/lib/annotator_alltoall_impl.cc \
        gr-blocks/lib/annotator_raw_impl.cc \
        gr-blocks/lib/argmax_impl.cc \
        gr-blocks/lib/bin_statistics_f_impl.cc \
        gr-blocks/lib/burst_tagger_impl.cc \
        gr-blocks/lib/char_to_float_impl.cc \
        gr-blocks/lib/char_to_short_impl.cc \
        gr-blocks/lib/check_lfsr_32k_s_impl.cc \
        gr-blocks/lib/complex_to_arg_impl.cc \
        gr-blocks/lib/complex_to_float_impl.cc \
        gr-blocks/lib/complex_to_imag_impl.cc \
        gr-blocks/lib/complex_to_interleaved_char_impl.cc \
        gr-blocks/lib/complex_to_interleaved_short_impl.cc \
        gr-blocks/lib/complex_to_mag_impl.cc \
        gr-blocks/lib/complex_to_mag_squared_impl.cc \
        gr-blocks/lib/complex_to_magphase_impl.cc \
        gr-blocks/lib/complex_to_real_impl.cc \
        gr-blocks/lib/conjugate_cc_impl.cc \
        gr-blocks/lib/control_loop.cc \
        gr-blocks/lib/copy_impl.cc \
        gr-blocks/lib/count_bits.cc \
        gr-blocks/lib/ctrlport_probe2_b_impl.cc \
        gr-blocks/lib/ctrlport_probe2_c_impl.cc \
        gr-blocks/lib/ctrlport_probe2_f_impl.cc \
        gr-blocks/lib/ctrlport_probe2_i_impl.cc \
        gr-blocks/lib/ctrlport_probe2_s_impl.cc \
        gr-blocks/lib/ctrlport_probe_c_impl.cc \
        gr-blocks/lib/deinterleave_impl.cc \
        gr-blocks/lib/delay_impl.cc \
        gr-blocks/lib/divide_impl.cc \
        gr-blocks/lib/endian_swap_impl.cc \
        gr-blocks/lib/exponentiate_const_cci_impl.cc \
        gr-blocks/lib/file_descriptor_sink_impl.cc \
        gr-blocks/lib/file_descriptor_source_impl.cc \
        gr-blocks/lib/file_meta_sink_impl.cc \
        gr-blocks/lib/file_meta_source_impl.cc \
        gr-blocks/lib/file_sink_base.cc \
        gr-blocks/lib/file_sink_impl.cc \
        gr-blocks/lib/file_source_impl.cc \
        gr-blocks/lib/float_array_to_int.cc \
        gr-blocks/lib/float_array_to_uchar.cc \
        gr-blocks/lib/float_to_char_impl.cc \
        gr-blocks/lib/float_to_complex_impl.cc \
        gr-blocks/lib/float_to_int_impl.cc \
        gr-blocks/lib/float_to_short_impl.cc \
        gr-blocks/lib/float_to_uchar_impl.cc \
        gr-blocks/lib/head_impl.cc \
        gr-blocks/lib/int_to_float_impl.cc \
        gr-blocks/lib/integrate_impl.cc \
        gr-blocks/lib/interleave_impl.cc \
        gr-blocks/lib/interleaved_char_to_complex_impl.cc \
        gr-blocks/lib/interleaved_short_array_to_complex.cc \
        gr-blocks/lib/interleaved_short_to_complex_impl.cc \
        gr-blocks/lib/keep_m_in_n_impl.cc \
        gr-blocks/lib/keep_one_in_n_impl.cc \
        gr-blocks/lib/lfsr_32k_source_s_impl.cc \
        gr-blocks/lib/magphase_to_complex_impl.cc \
        gr-blocks/lib/max_blk_impl.cc \
        gr-blocks/lib/message_debug_impl.cc \
        gr-blocks/lib/message_strobe_impl.cc \
        gr-blocks/lib/message_strobe_random_impl.cc \
        gr-blocks/lib/min_blk_impl.cc \
        gr-blocks/lib/moving_average_impl.cc \
        gr-blocks/lib/multiply_by_tag_value_cc_impl.cc \
        gr-blocks/lib/multiply_conjugate_cc_impl.cc \
        gr-blocks/lib/multiply_const_impl.cc \
        gr-blocks/lib/multiply_const_v_impl.cc \
        gr-blocks/lib/multiply_impl.cc \
        gr-blocks/lib/multiply_matrix_impl.cc \
        gr-blocks/lib/mute_impl.cc \
        gr-blocks/lib/nlog10_ff_impl.cc \
        gr-blocks/lib/nop_impl.cc \
        gr-blocks/lib/not_blk_impl.cc \
        gr-blocks/lib/null_sink_impl.cc \
        gr-blocks/lib/null_source_impl.cc \
        gr-blocks/lib/or_blk_impl.cc \
        gr-blocks/lib/pack_k_bits.cc \
        gr-blocks/lib/pack_k_bits_bb_impl.cc \
        gr-blocks/lib/packed_to_unpacked_impl.cc \
        gr-blocks/lib/patterned_interleaver_impl.cc \
        gr-blocks/lib/pdu.cc \
        gr-blocks/lib/pdu_filter_impl.cc \
        gr-blocks/lib/pdu_remove_impl.cc \
        gr-blocks/lib/pdu_set_impl.cc \
        gr-blocks/lib/pdu_to_tagged_stream_impl.cc \
        gr-blocks/lib/peak_detector2_fb_impl.cc \
        gr-blocks/lib/peak_detector_impl.cc \
        gr-blocks/lib/plateau_detector_fb_impl.cc \
        gr-blocks/lib/probe_rate_impl.cc \
        gr-blocks/lib/probe_signal_impl.cc \
        gr-blocks/lib/probe_signal_v_impl.cc \
        gr-blocks/lib/random_pdu_impl.cc \
        gr-blocks/lib/regenerate_bb_impl.cc \
        gr-blocks/lib/repack_bits_bb_impl.cc \
        gr-blocks/lib/repeat_impl.cc \
        gr-blocks/lib/rms_cf_impl.cc \
        gr-blocks/lib/rms_ff_impl.cc \
        gr-blocks/lib/rotator_cc_impl.cc \
        gr-blocks/lib/sample_and_hold_impl.cc \
        gr-blocks/lib/selector_impl.cc \
        gr-blocks/lib/short_to_char_impl.cc \
        gr-blocks/lib/short_to_float_impl.cc \
        gr-blocks/lib/skiphead_impl.cc \
        gr-blocks/lib/socket_pdu_impl.cc \
        gr-blocks/lib/stream_mux_impl.cc \
        gr-blocks/lib/stream_pdu_base.cc \
        gr-blocks/lib/stream_to_streams_impl.cc \
        gr-blocks/lib/stream_to_tagged_stream_impl.cc \
        gr-blocks/lib/stream_to_vector_impl.cc \
        gr-blocks/lib/streams_to_stream_impl.cc \
        gr-blocks/lib/streams_to_vector_impl.cc \
        gr-blocks/lib/stretch_ff_impl.cc \
        gr-blocks/lib/sub_impl.cc \
        gr-blocks/lib/tag_debug_impl.cc \
        gr-blocks/lib/tag_gate_impl.cc \
        gr-blocks/lib/tag_share_impl.cc \
        gr-blocks/lib/tagged_file_sink_impl.cc \
        gr-blocks/lib/tagged_stream_align_impl.cc \
        gr-blocks/lib/tagged_stream_multiply_length_impl.cc \
        gr-blocks/lib/tagged_stream_mux_impl.cc \
        gr-blocks/lib/tagged_stream_to_pdu_impl.cc \
        gr-blocks/lib/tags_strobe_impl.cc \
        gr-blocks/lib/tcp_connection.cc \
        gr-blocks/lib/tcp_server_sink_impl.cc \
        gr-blocks/lib/test_tag_variable_rate_ff_impl.cc \
        gr-blocks/lib/threshold_ff_impl.cc \
        gr-blocks/lib/throttle_impl.cc \
        gr-blocks/lib/transcendental_impl.cc \
        gr-blocks/lib/tsb_vector_sink_impl.cc \
        gr-blocks/lib/tuntap_pdu_impl.cc \
        gr-blocks/lib/uchar_array_to_float.cc \
        gr-blocks/lib/uchar_to_float_impl.cc \
        gr-blocks/lib/udp_sink_impl.cc \
        gr-blocks/lib/udp_source_impl.cc \
        gr-blocks/lib/unpack_k_bits.cc \
        gr-blocks/lib/unpack_k_bits_bb_impl.cc \
        gr-blocks/lib/unpacked_to_packed_impl.cc \
        gr-blocks/lib/vco_c_impl.cc \
        gr-blocks/lib/vco_f_impl.cc \
        gr-blocks/lib/vector_insert_impl.cc \
        gr-blocks/lib/vector_map_impl.cc \
        gr-blocks/lib/vector_sink_impl.cc \
        gr-blocks/lib/vector_source_impl.cc \
        gr-blocks/lib/vector_to_stream_impl.cc \
        gr-blocks/lib/vector_to_streams_impl.cc \
        gr-blocks/lib/wavfile.cc \
        gr-blocks/lib/wavfile_sink_impl.cc \
        gr-blocks/lib/wavfile_source_impl.cc \
        gr-blocks/lib/xor_blk_impl.cc \
        gnuradio-runtime/lib/realtime.cc \
        gnuradio-runtime/lib/realtime_impl.cc \
        gnuradio-runtime/lib/scheduler.cc \
        gnuradio-runtime/lib/scheduler_tpb.cc \
        gnuradio-runtime/lib/sptr_magic.cc \
        gnuradio-runtime/lib/sync_block.cc \
        gnuradio-runtime/lib/sync_decimator.cc \
        gnuradio-runtime/lib/sync_interpolator.cc \
        gnuradio-runtime/lib/sys_paths.cc \
        gnuradio-runtime/lib/tagged_stream_block.cc \
        gnuradio-runtime/lib/test.cc \
        gnuradio-runtime/lib/thread/thread.cc \
        gnuradio-runtime/lib/thread/thread_body_wrapper.cc \
        gnuradio-runtime/lib/thread/thread_group.cc \
        gnuradio-runtime/lib/top_block.cc \
        gnuradio-runtime/lib/top_block_impl.cc \
        gnuradio-runtime/lib/tpb_detail.cc \
        gnuradio-runtime/lib/tpb_thread_body.cc \
        gnuradio-runtime/lib/vmcircbuf.cc \
        gnuradio-runtime/lib/vmcircbuf_createfilemapping.cc \
        gnuradio-runtime/lib/vmcircbuf_mmap_shm_open.cc \
        gnuradio-runtime/lib/vmcircbuf_mmap_tmpfile.cc \
        gnuradio-runtime/lib/vmcircbuf_prefs.cc \
        gnuradio-runtime/lib/vmcircbuf_sysv_shm.cc \
        main.cpp \
        mainwindow.cpp

HEADERS += \
        gnuradio-runtime/include/gnuradio/api.h \
        gnuradio-runtime/include/gnuradio/attributes.h \
        gnuradio-runtime/include/gnuradio/basic_block.h \
        gnuradio-runtime/include/gnuradio/block.h \
        gnuradio-runtime/include/gnuradio/block_detail.h \
        gnuradio-runtime/include/gnuradio/block_gateway.h \
        gnuradio-runtime/include/gnuradio/block_registry.h \
        gnuradio-runtime/include/gnuradio/buffer.h \
        gnuradio-runtime/include/gnuradio/constants.h \
        gnuradio-runtime/include/gnuradio/endianness.h \
        gnuradio-runtime/include/gnuradio/expj.h \
        gnuradio-runtime/include/gnuradio/feval.h \
        gnuradio-runtime/include/gnuradio/flowgraph.h \
        gnuradio-runtime/include/gnuradio/fxpt.h \
        gnuradio-runtime/include/gnuradio/fxpt_nco.h \
        gnuradio-runtime/include/gnuradio/fxpt_vco.h \
        gnuradio-runtime/include/gnuradio/gr_complex.h \
        gnuradio-runtime/include/gnuradio/hier_block2.h \
        gnuradio-runtime/include/gnuradio/high_res_timer.h \
        gnuradio-runtime/include/gnuradio/io_signature.h \
        gnuradio-runtime/include/gnuradio/logger.h \
        gnuradio-runtime/include/gnuradio/math.h \
        gnuradio-runtime/include/gnuradio/message.h \
        gnuradio-runtime/include/gnuradio/messages/msg_accepter1.h \
        gnuradio-runtime/include/gnuradio/messages/msg_accepter_msgq.h \
        gnuradio-runtime/include/gnuradio/messages/msg_passing.h \
        gnuradio-runtime/include/gnuradio/messages/msg_producer.h \
        gnuradio-runtime/include/gnuradio/messages/msg_queue1.h \
        gnuradio-runtime/include/gnuradio/misc.h \
        gnuradio-runtime/include/gnuradio/msg_accepter.h \
        gnuradio-runtime/include/gnuradio/msg_handler.h \
        gnuradio-runtime/include/gnuradio/msg_queue.h \
        gnuradio-runtime/include/gnuradio/nco.h \
        gnuradio-runtime/include/gnuradio/prefs.h \
        gnuradio-runtime/include/gnuradio/py_feval.h \
        gnuradio-runtime/include/gnuradio/pycallback_object.h \
        gnuradio-runtime/include/gnuradio/random.h \
        gnuradio-runtime/include/gnuradio/realtime.h \
        gnuradio-runtime/include/gnuradio/realtime_impl.h \
        gnuradio-runtime/include/gnuradio/rpcbufferedget.h \
        gnuradio-runtime/include/gnuradio/rpccallbackregister_base.h \
        gnuradio-runtime/include/gnuradio/rpcmanager.h \
        gnuradio-runtime/include/gnuradio/rpcmanager_base.h \
        gnuradio-runtime/include/gnuradio/rpcpmtconverters_thrift.h \
        gnuradio-runtime/include/gnuradio/rpcregisterhelpers.h \
        gnuradio-runtime/include/gnuradio/rpcserver_aggregator.h \
        gnuradio-runtime/include/gnuradio/rpcserver_base.h \
        gnuradio-runtime/include/gnuradio/rpcserver_booter_aggregator.h \
        gnuradio-runtime/include/gnuradio/rpcserver_booter_base.h \
        gnuradio-runtime/include/gnuradio/rpcserver_selector.h \
        gnuradio-runtime/include/gnuradio/rpcserver_thrift.h \
        gnuradio-runtime/include/gnuradio/runtime_types.h \
        gnuradio-runtime/include/gnuradio/sincos.h \
        gnuradio-runtime/include/gnuradio/sptr_magic.h \
        gnuradio-runtime/include/gnuradio/sync_block.h \
        gnuradio-runtime/include/gnuradio/sync_decimator.h \
        gnuradio-runtime/include/gnuradio/sync_interpolator.h \
        gnuradio-runtime/include/gnuradio/sys_paths.h \
        gnuradio-runtime/include/gnuradio/tag_checker.h \
        gnuradio-runtime/include/gnuradio/tagged_stream_block.h \
        gnuradio-runtime/include/gnuradio/tags.h \
        gnuradio-runtime/include/gnuradio/thread/thread.h \
        gnuradio-runtime/include/gnuradio/thread/thread_body_wrapper.h \
        gnuradio-runtime/include/gnuradio/thread/thread_group.h \
        gnuradio-runtime/include/gnuradio/thrift_application_base.h \
        gnuradio-runtime/include/gnuradio/thrift_server_template.h \
        gnuradio-runtime/include/gnuradio/top_block.h \
        gnuradio-runtime/include/gnuradio/tpb_detail.h \
        gnuradio-runtime/include/gnuradio/types.h \
        gnuradio-runtime/include/gnuradio/unittests.h \
        gnuradio-runtime/include/gnuradio/xoroshiro128p.h \
        gnuradio-runtime/include/pmt/api.h \
        gnuradio-runtime/include/pmt/pmt.h \
        gnuradio-runtime/include/pmt/pmt_pool.h \
        gnuradio-runtime/include/pmt/pmt_serial_tags.h \
        gnuradio-runtime/include/pmt/pmt_sugar.h \
        gnuradio-runtime/lib/block_executor.h \
        gnuradio-runtime/lib/block_gateway_impl.h \
        gnuradio-runtime/lib/circular_file.h \
        gnuradio-runtime/lib/flat_flowgraph.h \
        gnuradio-runtime/lib/hier_block2_detail.h \
        gnuradio-runtime/lib/local_sighandler.h \
        gnuradio-runtime/lib/math/sine_table.h \
        gnuradio-runtime/lib/math/vco.h \
        gnuradio-runtime/lib/misc.h \
        gnuradio-runtime/lib/pagesize.h \
        gnuradio-runtime/lib/pmt/pmt_int.h \
        gnuradio-runtime/lib/pmt/pmt_unv_int.h \
        gnuradio-runtime/lib/scheduler.h \
        gnuradio-runtime/lib/scheduler_tpb.h \
        gnuradio-runtime/lib/test.h \
        gnuradio-runtime/lib/test_types.h \
        gnuradio-runtime/lib/threadexceptionhandle.h \
        gnuradio-runtime/lib/top_block_impl.h \
        gnuradio-runtime/lib/tpb_thread_body.h \
        gnuradio-runtime/lib/vmcircbuf.h \
        gnuradio-runtime/lib/vmcircbuf_createfilemapping.h \
        gnuradio-runtime/lib/vmcircbuf_mmap_shm_open.h \
        gnuradio-runtime/lib/vmcircbuf_mmap_tmpfile.h \
        gnuradio-runtime/lib/vmcircbuf_prefs.h \
        gnuradio-runtime/lib/vmcircbuf_sysv_shm.h \
        gr-beklBlk/include/beklBlk/RngLib.h \
        gr-beklBlk/include/beklBlk/api.h \
        gr-beklBlk/include/beklBlk/beklAmpAnalysis.h \
        gr-beklBlk/include/beklBlk/beklAntennaPrehandle.h \
        gr-beklBlk/include/beklBlk/beklUdpSource.h \
        gr-beklBlk/include/beklBlk/beklUdpSourece.h \
        gr-beklBlk/lib/beklAmpAnalysis_impl.h \
        gr-beklBlk/lib/beklAntennaPrehandle_impl.h \
        gr-beklBlk/lib/beklUdpSource_impl.h \
        gr-beklBlk/lib/beklUdpSourece_impl.h \
        gr-beklBlk/lib/qa_beklBlk.h \
        gr-blocks/include/gnuradio/blocks/abs_blk.h \
        gr-blocks/include/gnuradio/blocks/add_blk.h \
        gr-blocks/include/gnuradio/blocks/add_const_bb.h \
        gr-blocks/include/gnuradio/blocks/add_const_cc.h \
        gr-blocks/include/gnuradio/blocks/add_const_ff.h \
        gr-blocks/include/gnuradio/blocks/add_const_ii.h \
        gr-blocks/include/gnuradio/blocks/add_const_ss.h \
        gr-blocks/include/gnuradio/blocks/add_const_v.h \
        gr-blocks/include/gnuradio/blocks/and_blk.h \
        gr-blocks/include/gnuradio/blocks/and_const.h \
        gr-blocks/include/gnuradio/blocks/annotator_1to1.h \
        gr-blocks/include/gnuradio/blocks/annotator_alltoall.h \
        gr-blocks/include/gnuradio/blocks/annotator_raw.h \
        gr-blocks/include/gnuradio/blocks/api.h \
        gr-blocks/include/gnuradio/blocks/argmax.h \
        gr-blocks/include/gnuradio/blocks/bin_statistics_f.h \
        gr-blocks/include/gnuradio/blocks/burst_tagger.h \
        gr-blocks/include/gnuradio/blocks/char_to_float.h \
        gr-blocks/include/gnuradio/blocks/char_to_short.h \
        gr-blocks/include/gnuradio/blocks/check_lfsr_32k_s.h \
        gr-blocks/include/gnuradio/blocks/complex_to_arg.h \
        gr-blocks/include/gnuradio/blocks/complex_to_float.h \
        gr-blocks/include/gnuradio/blocks/complex_to_imag.h \
        gr-blocks/include/gnuradio/blocks/complex_to_interleaved_char.h \
        gr-blocks/include/gnuradio/blocks/complex_to_interleaved_short.h \
        gr-blocks/include/gnuradio/blocks/complex_to_mag.h \
        gr-blocks/include/gnuradio/blocks/complex_to_mag_squared.h \
        gr-blocks/include/gnuradio/blocks/complex_to_magphase.h \
        gr-blocks/include/gnuradio/blocks/complex_to_real.h \
        gr-blocks/include/gnuradio/blocks/conjugate_cc.h \
        gr-blocks/include/gnuradio/blocks/control_loop.h \
        gr-blocks/include/gnuradio/blocks/copy.h \
        gr-blocks/include/gnuradio/blocks/count_bits.h \
        gr-blocks/include/gnuradio/blocks/ctrlport_probe2_b.h \
        gr-blocks/include/gnuradio/blocks/ctrlport_probe2_c.h \
        gr-blocks/include/gnuradio/blocks/ctrlport_probe2_f.h \
        gr-blocks/include/gnuradio/blocks/ctrlport_probe2_i.h \
        gr-blocks/include/gnuradio/blocks/ctrlport_probe2_s.h \
        gr-blocks/include/gnuradio/blocks/ctrlport_probe_c.h \
        gr-blocks/include/gnuradio/blocks/deinterleave.h \
        gr-blocks/include/gnuradio/blocks/delay.h \
        gr-blocks/include/gnuradio/blocks/divide.h \
        gr-blocks/include/gnuradio/blocks/endian_swap.h \
        gr-blocks/include/gnuradio/blocks/exponentiate_const_cci.h \
        gr-blocks/include/gnuradio/blocks/file_descriptor_sink.h \
        gr-blocks/include/gnuradio/blocks/file_descriptor_source.h \
        gr-blocks/include/gnuradio/blocks/file_meta_sink.h \
        gr-blocks/include/gnuradio/blocks/file_meta_source.h \
        gr-blocks/include/gnuradio/blocks/file_sink.h \
        gr-blocks/include/gnuradio/blocks/file_sink_base.h \
        gr-blocks/include/gnuradio/blocks/file_source.h \
        gr-blocks/include/gnuradio/blocks/float_to_char.h \
        gr-blocks/include/gnuradio/blocks/float_to_complex.h \
        gr-blocks/include/gnuradio/blocks/float_to_int.h \
        gr-blocks/include/gnuradio/blocks/float_to_short.h \
        gr-blocks/include/gnuradio/blocks/float_to_uchar.h \
        gr-blocks/include/gnuradio/blocks/head.h \
        gr-blocks/include/gnuradio/blocks/int_to_float.h \
        gr-blocks/include/gnuradio/blocks/integrate.h \
        gr-blocks/include/gnuradio/blocks/interleave.h \
        gr-blocks/include/gnuradio/blocks/interleaved_char_to_complex.h \
        gr-blocks/include/gnuradio/blocks/interleaved_short_to_complex.h \
        gr-blocks/include/gnuradio/blocks/keep_m_in_n.h \
        gr-blocks/include/gnuradio/blocks/keep_one_in_n.h \
        gr-blocks/include/gnuradio/blocks/lfsr_15_1_0.h \
        gr-blocks/include/gnuradio/blocks/lfsr_32k.h \
        gr-blocks/include/gnuradio/blocks/lfsr_32k_source_s.h \
        gr-blocks/include/gnuradio/blocks/log2_const.h \
        gr-blocks/include/gnuradio/blocks/magphase_to_complex.h \
        gr-blocks/include/gnuradio/blocks/max_blk.h \
        gr-blocks/include/gnuradio/blocks/message_debug.h \
        gr-blocks/include/gnuradio/blocks/message_strobe.h \
        gr-blocks/include/gnuradio/blocks/message_strobe_random.h \
        gr-blocks/include/gnuradio/blocks/min_blk.h \
        gr-blocks/include/gnuradio/blocks/moving_average.h \
        gr-blocks/include/gnuradio/blocks/multiply.h \
        gr-blocks/include/gnuradio/blocks/multiply_by_tag_value_cc.h \
        gr-blocks/include/gnuradio/blocks/multiply_conjugate_cc.h \
        gr-blocks/include/gnuradio/blocks/multiply_const.h \
        gr-blocks/include/gnuradio/blocks/multiply_const_v.h \
        gr-blocks/include/gnuradio/blocks/multiply_matrix.h \
        gr-blocks/include/gnuradio/blocks/mute.h \
        gr-blocks/include/gnuradio/blocks/nlog10_ff.h \
        gr-blocks/include/gnuradio/blocks/nop.h \
        gr-blocks/include/gnuradio/blocks/not_blk.h \
        gr-blocks/include/gnuradio/blocks/null_sink.h \
        gr-blocks/include/gnuradio/blocks/null_source.h \
        gr-blocks/include/gnuradio/blocks/or_blk.h \
        gr-blocks/include/gnuradio/blocks/pack_k_bits.h \
        gr-blocks/include/gnuradio/blocks/pack_k_bits_bb.h \
        gr-blocks/include/gnuradio/blocks/packed_to_unpacked.h \
        gr-blocks/include/gnuradio/blocks/patterned_interleaver.h \
        gr-blocks/include/gnuradio/blocks/pdu.h \
        gr-blocks/include/gnuradio/blocks/pdu_filter.h \
        gr-blocks/include/gnuradio/blocks/pdu_remove.h \
        gr-blocks/include/gnuradio/blocks/pdu_set.h \
        gr-blocks/include/gnuradio/blocks/pdu_to_tagged_stream.h \
        gr-blocks/include/gnuradio/blocks/peak_detector.h \
        gr-blocks/include/gnuradio/blocks/peak_detector2_fb.h \
        gr-blocks/include/gnuradio/blocks/plateau_detector_fb.h \
        gr-blocks/include/gnuradio/blocks/probe_rate.h \
        gr-blocks/include/gnuradio/blocks/probe_signal.h \
        gr-blocks/include/gnuradio/blocks/probe_signal_v.h \
        gr-blocks/include/gnuradio/blocks/random_pdu.h \
        gr-blocks/include/gnuradio/blocks/regenerate_bb.h \
        gr-blocks/include/gnuradio/blocks/repack_bits_bb.h \
        gr-blocks/include/gnuradio/blocks/repeat.h \
        gr-blocks/include/gnuradio/blocks/rms_cf.h \
        gr-blocks/include/gnuradio/blocks/rms_ff.h \
        gr-blocks/include/gnuradio/blocks/rotator.h \
        gr-blocks/include/gnuradio/blocks/rotator_cc.h \
        gr-blocks/include/gnuradio/blocks/sample_and_hold.h \
        gr-blocks/include/gnuradio/blocks/selector.h \
        gr-blocks/include/gnuradio/blocks/short_to_char.h \
        gr-blocks/include/gnuradio/blocks/short_to_float.h \
        gr-blocks/include/gnuradio/blocks/skiphead.h \
        gr-blocks/include/gnuradio/blocks/socket_pdu.h \
        gr-blocks/include/gnuradio/blocks/stream_mux.h \
        gr-blocks/include/gnuradio/blocks/stream_to_streams.h \
        gr-blocks/include/gnuradio/blocks/stream_to_tagged_stream.h \
        gr-blocks/include/gnuradio/blocks/stream_to_vector.h \
        gr-blocks/include/gnuradio/blocks/streams_to_stream.h \
        gr-blocks/include/gnuradio/blocks/streams_to_vector.h \
        gr-blocks/include/gnuradio/blocks/stretch_ff.h \
        gr-blocks/include/gnuradio/blocks/sub.h \
        gr-blocks/include/gnuradio/blocks/tag_debug.h \
        gr-blocks/include/gnuradio/blocks/tag_gate.h \
        gr-blocks/include/gnuradio/blocks/tag_share.h \
        gr-blocks/include/gnuradio/blocks/tagged_file_sink.h \
        gr-blocks/include/gnuradio/blocks/tagged_stream_align.h \
        gr-blocks/include/gnuradio/blocks/tagged_stream_multiply_length.h \
        gr-blocks/include/gnuradio/blocks/tagged_stream_mux.h \
        gr-blocks/include/gnuradio/blocks/tagged_stream_to_pdu.h \
        gr-blocks/include/gnuradio/blocks/tags_strobe.h \
        gr-blocks/include/gnuradio/blocks/tcp_server_sink.h \
        gr-blocks/include/gnuradio/blocks/test_tag_variable_rate_ff.h \
        gr-blocks/include/gnuradio/blocks/threshold_ff.h \
        gr-blocks/include/gnuradio/blocks/throttle.h \
        gr-blocks/include/gnuradio/blocks/transcendental.h \
        gr-blocks/include/gnuradio/blocks/tsb_vector_sink.h \
        gr-blocks/include/gnuradio/blocks/tuntap_pdu.h \
        gr-blocks/include/gnuradio/blocks/uchar_to_float.h \
        gr-blocks/include/gnuradio/blocks/udp_sink.h \
        gr-blocks/include/gnuradio/blocks/udp_source.h \
        gr-blocks/include/gnuradio/blocks/unpack_k_bits.h \
        gr-blocks/include/gnuradio/blocks/unpack_k_bits_bb.h \
        gr-blocks/include/gnuradio/blocks/unpacked_to_packed.h \
        gr-blocks/include/gnuradio/blocks/vco_c.h \
        gr-blocks/include/gnuradio/blocks/vco_f.h \
        gr-blocks/include/gnuradio/blocks/vector_insert.h \
        gr-blocks/include/gnuradio/blocks/vector_map.h \
        gr-blocks/include/gnuradio/blocks/vector_sink.h \
        gr-blocks/include/gnuradio/blocks/vector_source.h \
        gr-blocks/include/gnuradio/blocks/vector_to_stream.h \
        gr-blocks/include/gnuradio/blocks/vector_to_streams.h \
        gr-blocks/include/gnuradio/blocks/wavfile.h \
        gr-blocks/include/gnuradio/blocks/wavfile_sink.h \
        gr-blocks/include/gnuradio/blocks/wavfile_source.h \
        gr-blocks/include/gnuradio/blocks/xor_blk.h \
        gr-blocks/lib/abs_blk_impl.h \
        gr-blocks/lib/add_blk_impl.h \
        gr-blocks/lib/add_const_bb_impl.h \
        gr-blocks/lib/add_const_cc_impl.h \
        gr-blocks/lib/add_const_ff_impl.h \
        gr-blocks/lib/add_const_ii_impl.h \
        gr-blocks/lib/add_const_ss_impl.h \
        gr-blocks/lib/add_const_v_impl.h \
        gr-blocks/lib/and_blk_impl.h \
        gr-blocks/lib/and_const_impl.h \
        gr-blocks/lib/annotator_1to1_impl.h \
        gr-blocks/lib/annotator_alltoall_impl.h \
        gr-blocks/lib/annotator_raw_impl.h \
        gr-blocks/lib/argmax_impl.h \
        gr-blocks/lib/bin_statistics_f_impl.h \
        gr-blocks/lib/burst_tagger_impl.h \
        gr-blocks/lib/char_to_float_impl.h \
        gr-blocks/lib/char_to_short_impl.h \
        gr-blocks/lib/check_lfsr_32k_s_impl.h \
        gr-blocks/lib/complex_to_arg_impl.h \
        gr-blocks/lib/complex_to_float_impl.h \
        gr-blocks/lib/complex_to_imag_impl.h \
        gr-blocks/lib/complex_to_interleaved_char_impl.h \
        gr-blocks/lib/complex_to_interleaved_short_impl.h \
        gr-blocks/lib/complex_to_mag_impl.h \
        gr-blocks/lib/complex_to_mag_squared_impl.h \
        gr-blocks/lib/complex_to_magphase_impl.h \
        gr-blocks/lib/complex_to_real_impl.h \
        gr-blocks/lib/conjugate_cc_impl.h \
        gr-blocks/lib/copy_impl.h \
        gr-blocks/lib/ctrlport_probe2_b_impl.h \
        gr-blocks/lib/ctrlport_probe2_c_impl.h \
        gr-blocks/lib/ctrlport_probe2_f_impl.h \
        gr-blocks/lib/ctrlport_probe2_i_impl.h \
        gr-blocks/lib/ctrlport_probe2_s_impl.h \
        gr-blocks/lib/ctrlport_probe_c_impl.h \
        gr-blocks/lib/deinterleave_impl.h \
        gr-blocks/lib/delay_impl.h \
        gr-blocks/lib/divide_impl.h \
        gr-blocks/lib/endian_swap_impl.h \
        gr-blocks/lib/exponentiate_const_cci_impl.h \
        gr-blocks/lib/file_descriptor_sink_impl.h \
        gr-blocks/lib/file_descriptor_source_impl.h \
        gr-blocks/lib/file_meta_sink_impl.h \
        gr-blocks/lib/file_meta_source_impl.h \
        gr-blocks/lib/file_sink_impl.h \
        gr-blocks/lib/file_source_impl.h \
        gr-blocks/lib/float_array_to_int.h \
        gr-blocks/lib/float_array_to_uchar.h \
        gr-blocks/lib/float_to_char_impl.h \
        gr-blocks/lib/float_to_complex_impl.h \
        gr-blocks/lib/float_to_int_impl.h \
        gr-blocks/lib/float_to_short_impl.h \
        gr-blocks/lib/float_to_uchar_impl.h \
        gr-blocks/lib/gnuradio-blocks.rc.in \
        gr-blocks/lib/head_impl.h \
        gr-blocks/lib/int_to_float_impl.h \
        gr-blocks/lib/integrate_impl.h \
        gr-blocks/lib/interleave_impl.h \
        gr-blocks/lib/interleaved_char_to_complex_impl.h \
        gr-blocks/lib/interleaved_short_array_to_complex.h \
        gr-blocks/lib/interleaved_short_to_complex_impl.h \
        gr-blocks/lib/keep_m_in_n_impl.h \
        gr-blocks/lib/keep_one_in_n_impl.h \
        gr-blocks/lib/lfsr_32k_source_s_impl.h \
        gr-blocks/lib/magphase_to_complex_impl.h \
        gr-blocks/lib/max_blk_impl.h \
        gr-blocks/lib/message_debug_impl.h \
        gr-blocks/lib/message_strobe_impl.h \
        gr-blocks/lib/message_strobe_random_impl.h \
        gr-blocks/lib/min_blk_impl.h \
        gr-blocks/lib/moving_average_impl.h \
        gr-blocks/lib/multiply_by_tag_value_cc_impl.h \
        gr-blocks/lib/multiply_conjugate_cc_impl.h \
        gr-blocks/lib/multiply_const_impl.h \
        gr-blocks/lib/multiply_const_v_impl.h \
        gr-blocks/lib/multiply_impl.h \
        gr-blocks/lib/multiply_matrix_impl.h \
        gr-blocks/lib/mute_impl.h \
        gr-blocks/lib/nlog10_ff_impl.h \
        gr-blocks/lib/nop_impl.h \
        gr-blocks/lib/not_blk_impl.h \
        gr-blocks/lib/null_sink_impl.h \
        gr-blocks/lib/null_source_impl.h \
        gr-blocks/lib/or_blk_impl.h \
        gr-blocks/lib/pack_k_bits_bb_impl.h \
        gr-blocks/lib/packed_to_unpacked_impl.h \
        gr-blocks/lib/patterned_interleaver_impl.h \
        gr-blocks/lib/pdu_filter_impl.h \
        gr-blocks/lib/pdu_remove_impl.h \
        gr-blocks/lib/pdu_set_impl.h \
        gr-blocks/lib/pdu_to_tagged_stream_impl.h \
        gr-blocks/lib/peak_detector2_fb_impl.h \
        gr-blocks/lib/peak_detector_impl.h \
        gr-blocks/lib/plateau_detector_fb_impl.h \
        gr-blocks/lib/probe_rate_impl.h \
        gr-blocks/lib/probe_signal_impl.h \
        gr-blocks/lib/probe_signal_v_impl.h \
        gr-blocks/lib/random_pdu_impl.h \
        gr-blocks/lib/regenerate_bb_impl.h \
        gr-blocks/lib/repack_bits_bb_impl.h \
        gr-blocks/lib/repeat_impl.h \
        gr-blocks/lib/rms_cf_impl.h \
        gr-blocks/lib/rms_ff_impl.h \
        gr-blocks/lib/rotator_cc_impl.h \
        gr-blocks/lib/sample_and_hold_impl.h \
        gr-blocks/lib/selector_impl.h \
        gr-blocks/lib/short_to_char_impl.h \
        gr-blocks/lib/short_to_float_impl.h \
        gr-blocks/lib/skiphead_impl.h \
        gr-blocks/lib/socket_pdu_impl.h \
        gr-blocks/lib/stream_mux_impl.h \
        gr-blocks/lib/stream_pdu_base.h \
        gr-blocks/lib/stream_to_streams_impl.h \
        gr-blocks/lib/stream_to_tagged_stream_impl.h \
        gr-blocks/lib/stream_to_vector_impl.h \
        gr-blocks/lib/streams_to_stream_impl.h \
        gr-blocks/lib/streams_to_vector_impl.h \
        gr-blocks/lib/stretch_ff_impl.h \
        gr-blocks/lib/sub_impl.h \
        gr-blocks/lib/tag_debug_impl.h \
        gr-blocks/lib/tag_gate_impl.h \
        gr-blocks/lib/tag_share_impl.h \
        gr-blocks/lib/tagged_file_sink_impl.h \
        gr-blocks/lib/tagged_stream_align_impl.h \
        gr-blocks/lib/tagged_stream_multiply_length_impl.h \
        gr-blocks/lib/tagged_stream_mux_impl.h \
        gr-blocks/lib/tagged_stream_to_pdu_impl.h \
        gr-blocks/lib/tags_strobe_impl.h \
        gr-blocks/lib/tcp_connection.h \
        gr-blocks/lib/tcp_server_sink_impl.h \
        gr-blocks/lib/test_tag_variable_rate_ff_impl.h \
        gr-blocks/lib/threshold_ff_impl.h \
        gr-blocks/lib/throttle_impl.h \
        gr-blocks/lib/transcendental_impl.h \
        gr-blocks/lib/tsb_vector_sink_impl.h \
        gr-blocks/lib/tuntap_pdu_impl.h \
        gr-blocks/lib/uchar_array_to_float.h \
        gr-blocks/lib/uchar_to_float_impl.h \
        gr-blocks/lib/udp_sink_impl.h \
        gr-blocks/lib/udp_source_impl.h \
        gr-blocks/lib/unpack_k_bits_bb_impl.h \
        gr-blocks/lib/unpacked_to_packed_impl.h \
        gr-blocks/lib/vco_c_impl.h \
        gr-blocks/lib/vco_f_impl.h \
        gr-blocks/lib/vector_insert_impl.h \
        gr-blocks/lib/vector_map_impl.h \
        gr-blocks/lib/vector_sink_impl.h \
        gr-blocks/lib/vector_source_impl.h \
        gr-blocks/lib/vector_to_stream_impl.h \
        gr-blocks/lib/vector_to_streams_impl.h \
        gr-blocks/lib/wavfile_sink_impl.h \
        gr-blocks/lib/wavfile_source_impl.h \
        gr-blocks/lib/xor_blk_impl.h \
        mainwindow.h

FORMS += \
        mainwindow.ui

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target


